{"uuid": "c040ba9b-0255-4c00-a122-664878e6c8f8", "children": ["1a37764c-4b9e-437f-90ae-b18b3a895e38"], "befores": [{"name": "login_user", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: Element <button class=\"button_button__33qZ0 button_button_type_primary__1O7Bx button_button_size_medium__3zxIa\"> is not clickable at point (640,549) because another element <div class=\"Modal_modal_overlay__x2ZCr\"> obscures it\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nElementClickInterceptedError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:337:5\nwebdriverClickElement@chrome://remote/content/marionette/interaction.sys.mjs:177:11\ninteraction.clickElement@chrome://remote/content/marionette/interaction.sys.mjs:136:11\nclickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:205:29\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:85:31\n\n", "trace": "  File \"/Users/osneg/Desktop/Diplom/Diplom_3/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Users/osneg/Desktop/Diplom/Diplom_3/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/osneg/Desktop/Diplom/Diplom_3/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/osneg/Desktop/Diplom/Diplom_3/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/osneg/Desktop/Diplom/Diplom_3/lib/python3.12/site-packages/_pytest/fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/osneg/Desktop/Diplom/Diplom_3/tests/conftest.py\", line 49, in login_user\n    login_page.input_user_data(client['email'], client['password'])\n  File \"/Users/osneg/Desktop/Diplom/Diplom_3/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/osneg/Desktop/Diplom/Diplom_3/pages/login_page.py\", line 19, in input_user_data\n    self.click_element(LoginPageLocators.ENTER_BUTTON)\n  File \"/Users/osneg/Desktop/Diplom/Diplom_3/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/osneg/Desktop/Diplom/Diplom_3/pages/base_page.py\", line 14, in click_element\n    self.driver.find_element(*locator).click()\n  File \"/Users/osneg/Desktop/Diplom/Diplom_3/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py\", line 94, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"/Users/osneg/Desktop/Diplom/Diplom_3/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py\", line 395, in _execute\n    return self._parent.execute(command, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/osneg/Desktop/Diplom/Diplom_3/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/osneg/Desktop/Diplom/Diplom_3/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Авторизуем пользователя", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: Element <button class=\"button_button__33qZ0 button_button_type_primary__1O7Bx button_button_size_medium__3zxIa\"> is not clickable at point (640,549) because another element <div class=\"Modal_modal_overlay__x2ZCr\"> obscures it\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nElementClickInterceptedError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:337:5\nwebdriverClickElement@chrome://remote/content/marionette/interaction.sys.mjs:177:11\ninteraction.clickElement@chrome://remote/content/marionette/interaction.sys.mjs:136:11\nclickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:205:29\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:85:31\n\n", "trace": "  File \"/Users/osneg/Desktop/Diplom/Diplom_3/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/osneg/Desktop/Diplom/Diplom_3/pages/login_page.py\", line 19, in input_user_data\n    self.click_element(LoginPageLocators.ENTER_BUTTON)\n  File \"/Users/osneg/Desktop/Diplom/Diplom_3/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/osneg/Desktop/Diplom/Diplom_3/pages/base_page.py\", line 14, in click_element\n    self.driver.find_element(*locator).click()\n  File \"/Users/osneg/Desktop/Diplom/Diplom_3/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py\", line 94, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"/Users/osneg/Desktop/Diplom/Diplom_3/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py\", line 395, in _execute\n    return self._parent.execute(command, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/osneg/Desktop/Diplom/Diplom_3/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/osneg/Desktop/Diplom/Diplom_3/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Заполняем поле \"email\"", "status": "passed", "steps": [{"name": "Заполняем поле данными", "status": "passed", "parameters": [{"name": "locator", "value": "('xpath', \".//input[@name = 'name']\")"}, {"name": "text", "value": "'29b2kg9.@gmail.com'"}], "start": 1728506572021, "stop": 1728506572068}], "parameters": [{"name": "email", "value": "'29b2kg9.@gmail.com'"}], "start": 1728506572021, "stop": 1728506572068}, {"name": "Заполняем поле \"Пароль\"", "status": "passed", "steps": [{"name": "Заполняем поле данными", "status": "passed", "parameters": [{"name": "locator", "value": "('xpath', \".//input[@name = 'Пароль']\")"}, {"name": "text", "value": "'ncrm40'"}], "start": 1728506572068, "stop": 1728506572081}], "parameters": [{"name": "password", "value": "'ncrm40'"}], "start": 1728506572068, "stop": 1728506572081}, {"name": "Кликаем по элементу", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: Element <button class=\"button_button__33qZ0 button_button_type_primary__1O7Bx button_button_size_medium__3zxIa\"> is not clickable at point (640,549) because another element <div class=\"Modal_modal_overlay__x2ZCr\"> obscures it\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nElementClickInterceptedError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:337:5\nwebdriverClickElement@chrome://remote/content/marionette/interaction.sys.mjs:177:11\ninteraction.clickElement@chrome://remote/content/marionette/interaction.sys.mjs:136:11\nclickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:205:29\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:85:31\n\n", "trace": "  File \"/Users/osneg/Desktop/Diplom/Diplom_3/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/osneg/Desktop/Diplom/Diplom_3/pages/base_page.py\", line 14, in click_element\n    self.driver.find_element(*locator).click()\n  File \"/Users/osneg/Desktop/Diplom/Diplom_3/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py\", line 94, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"/Users/osneg/Desktop/Diplom/Diplom_3/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py\", line 395, in _execute\n    return self._parent.execute(command, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/osneg/Desktop/Diplom/Diplom_3/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/osneg/Desktop/Diplom/Diplom_3/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "parameters": [{"name": "locator", "value": "('xpath', \".//button[text() = 'Войти']\")"}], "start": 1728506572081, "stop": 1728506572087}], "parameters": [{"name": "email", "value": "'29b2kg9.@gmail.com'"}, {"name": "password", "value": "'ncrm40'"}], "start": 1728506572020, "stop": 1728506572088}], "start": 1728506571394, "stop": 1728506572088}], "start": 1728506571394, "stop": 1728506572104}